package GUI;

import com.formdev.flatlaf.FlatIntelliJLaf;
import java.util.LinkedList;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import logic.Token;

public class TokensTable extends javax.swing.JFrame {

    public static LinkedList<Token> tokensList = new LinkedList<>();

    public TokensTable() {
        initComponents();
        this.setLocationRelativeTo(null);
        printTable();
    }

    private void printTable() {
        DefaultTableModel tableModel = (DefaultTableModel) tokensTable.getModel();
        
        int number = 1;
        Object[] row;
        
        for (int i = 0; i < tokensList.size(); i++) {
            row = new Object[5];
            row[0] = number;
            row[1] = tokensList.get(i).getLexeme();
            row[2] = tokensList.get(i).getType();
            row[3] = tokensList.get(i).getLine();
            row[4] = tokensList.get(i).getColumn();
            
            tableModel.addRow(row);
            number++;
        }
        
        centerTable();
    }
    
    private void centerTable() {
        DefaultTableCellRenderer cellRenderer = new DefaultTableCellRenderer();
        cellRenderer.setHorizontalAlignment(SwingConstants.CENTER);
        
        for (int i = 0; i < tokensTable.getColumnCount(); i++) {
            tokensTable.getColumnModel().getColumn(i).setCellRenderer(cellRenderer);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tokensTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tabla de Tokens");
        setResizable(false);

        tokensTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Lexema", "Tipo", "Línea", "Columna"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tokensTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tokensTable);
        if (tokensTable.getColumnModel().getColumnCount() > 0) {
            tokensTable.getColumnModel().getColumn(0).setResizable(false);
            tokensTable.getColumnModel().getColumn(0).setPreferredWidth(10);
            tokensTable.getColumnModel().getColumn(1).setResizable(false);
            tokensTable.getColumnModel().getColumn(2).setResizable(false);
            tokensTable.getColumnModel().getColumn(3).setResizable(false);
            tokensTable.getColumnModel().getColumn(3).setPreferredWidth(10);
            tokensTable.getColumnModel().getColumn(4).setResizable(false);
            tokensTable.getColumnModel().getColumn(4).setPreferredWidth(10);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 880, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatIntelliJLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TokensTable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tokensTable;
    // End of variables declaration//GEN-END:variables
}
